name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "New Features"
    labels:
      - "enhancement"
      - "feature"
  - title: "Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "Dependencies"
    labels:
      - "dependencies"
  - title: "Documentation"
    labels:
      - "documentation"
  - title: "CI/CD"
    labels:
      - "ci"
  - title: "Other Changes"
    labels:
      - "*"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "enhancement"
      - "feature"
  patch:
    labels:
      - "bug"
      - "fix"
      - "dependencies"
  default: patch
template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
